# Generated by Django 2.2.1 on 2019-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='名字')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('cellphone', models.CharField(max_length=20, verbose_name='手机')),
                ('fax', models.CharField(max_length=20, verbose_name='传真')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('postcode', models.CharField(max_length=20, verbose_name='邮编')),
                ('address', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=20, verbose_name='制造：')),
                ('Model', models.CharField(max_length=20, verbose_name='模型')),
                ('MFG', models.CharField(max_length=20, verbose_name='生产日期')),
                ('Mileage', models.CharField(max_length=20, verbose_name='里程数')),
                ('Power', models.CharField(max_length=20, verbose_name='动力')),
                ('Fuel', models.CharField(max_length=20, verbose_name='燃料')),
                ('Gearbox', models.CharField(max_length=20, verbose_name='变速箱')),
                ('Number', models.CharField(max_length=20, verbose_name='座位数')),
                ('Doors', models.CharField(max_length=20, verbose_name='门')),
                ('EC', models.CharField(max_length=20, verbose_name='排放等级')),
                ('VT', models.CharField(max_length=20, verbose_name='车辆类型')),
                ('Color', models.CharField(max_length=20, verbose_name='颜色')),
                ('Airbags', models.CharField(max_length=20, verbose_name='安全气囊')),
                ('CC', models.CharField(max_length=20, verbose_name='气候控制')),
                ('DV', models.CharField(max_length=20, verbose_name='损坏车辆')),
                ('feature', models.TextField()),
                ('describe', models.TextField()),
            ],
        ),
    ]
