# Generated by Django 2.2.1 on 2019-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='parameter',
            name='describe',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='feature',
            field=models.TextField(max_length=100, verbose_name='特征'),
        ),
    ]
