# Generated by Django 2.2.1 on 2019-05-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20190529_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品牌：')),
                ('price', models.IntegerField(default=0, verbose_name='价钱')),
                ('img', models.ImageField(upload_to='ads', verbose_name='图片')),
                ('parame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.parameter')),
            ],
        ),


    ]
