# Generated by Django 2.2.1 on 2019-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20190529_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=10, verbose_name='首页')),
                ('style', models.CharField(max_length=10, verbose_name='车型')),
                ('about', models.CharField(max_length=10, verbose_name='关于')),
                ('contact', models.CharField(max_length=10, verbose_name='联系')),
            ],
        ),

    ]
