# Generated by Django 2.2.1 on 2019-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20190530_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('fea', models.CharField(max_length=20, verbose_name='特征')),
                ('dep', models.CharField(max_length=20, verbose_name='描述')),
            ],
        ),
    ]
