# Generated by Django 2.2.1 on 2019-05-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190515_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_data',
            field=models.DateTimeField(verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=30, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.Account')),
            ],
        ),
    ]
