# Generated by Django 2.2.1 on 2019-05-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190523_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ceate_time',
            new_name='create_time',
        ),
    ]
